[package]
name = "signarm-signal-launcher"
version = "0.1.0"
edition = "2021"
description = "Self-extracting single-file launcher for Signarm Signal"

[[bin]]
name = "SignarmSignal"
path = "src/main.rs"

[dependencies]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "z"
strip = true
